# Generated by Django 4.2.30 on 2026-08-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0007_project_customer_name_project_project_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacityPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(default='Default Plan', max_length=256)),
                ('year', models.IntegerField(default=2026)),
                ('horizon', models.CharField(default='Aug 2026 - Jul 2027', max_length=128)),
                ('tasks', models.JSONField(default=list)),
                ('total_hours', models.FloatField(default=140000.0)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
