# Generated by Django 4.2.30 on 2026-08-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0011_project_so_line_items_project_so_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='qty',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
